import type {
  Brand,
  City,
  ComparisonPage,
  Dealer,
  DealerBrandMapping,
  GstRule,
  HeroPromotion,
  InsuranceRule,
  Offer,
  RegistrationFeeRule,
  RtoCharge,
  RtoOffice,
  SeoPage,
  State,
  StateTaxRule,
  VehicleCategory,
  VehicleLead,
  VehicleMedia,
  VehicleModel,
  SpecificationGroup,
  VehicleSpecifications,
  VehicleVariant,
} from "@/types/automobile";

export const categories: VehicleCategory[] = [
  { id: "cat-car", name: "Cars", slug: "cars", description: "Hatchbacks, sedans, SUVs and MUVs." },
  { id: "cat-bike", name: "Bikes", slug: "bikes", description: "Commuter, cruiser and performance bikes." },
  { id: "cat-scooter", name: "Scooters", slug: "scooters", description: "ICE and electric scooters." },
  { id: "cat-ev", name: "EV Vehicles", slug: "ev-vehicles", description: "Electric cars, scooters and bikes." },
  { id: "cat-commercial", name: "Commercial Vehicles", slug: "commercial-vehicles", description: "Trucks, pickups, buses and fleet vehicles." },
  { id: "cat-ev-commercial", name: "EV Commercial Vehicles", slug: "ev-commercial-vehicles", description: "Electric cargo, fleet and commercial mobility." },
];

export const brands: Brand[] = [
  { id: "brand-hyundai", name: "Hyundai", slug: "hyundai", active: true, featured: true },
  { id: "brand-tata", name: "Tata", slug: "tata", active: true, featured: true },
  { id: "brand-mahindra", name: "Mahindra", slug: "mahindra", active: true, featured: true },
  { id: "brand-ather", name: "Ather", slug: "ather", active: true, featured: true },
  { id: "brand-maruti", name: "Maruti Suzuki", slug: "maruti-suzuki", active: true, featured: false },
  { id: "brand-royal-enfield", name: "Royal Enfield", slug: "royal-enfield", active: true, featured: true },
  { id: "brand-ashok-leyland", name: "Ashok Leyland", slug: "ashok-leyland", active: true, featured: false },
  { id: "brand-euler", name: "Euler Motors", slug: "euler-motors", active: true, featured: false },
];

export const models: VehicleModel[] = [
  {
    id: "model-creta",
    brandId: "brand-hyundai",
    categoryId: "cat-car",
    name: "Creta",
    slug: "creta",
    bodyType: "SUV",
    imageUrl:
      "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=900&q=80",
    overview:
      "Hyundai Creta is positioned as a practical midsize SUV for city and highway users who want a comfortable cabin, strong feature list and multiple petrol/diesel automatic choices. The on-road price varies meaningfully by city because road tax, registration, insurance and dealer-level offers change by state and dealer mapping.",
    pros: ["Strong variant spread", "Premium cabin feel", "Diesel automatic option", "Good resale interest"],
    cons: ["Top variants can become expensive", "Waiting period may vary by city", "Some features are variant-specific"],
    active: true,
    featured: true,
    launchLabel: "Popular SUV",
  },
  {
    id: "model-nexon",
    brandId: "brand-tata",
    categoryId: "cat-car",
    name: "Nexon",
    slug: "nexon",
    bodyType: "Compact SUV",
    imageUrl:
      "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=900&q=80",
    overview:
      "Tata Nexon is a compact SUV focused on safety, high ground clearance and city-friendly size. It works well for buyers comparing value, safety credentials and running cost.",
    pros: ["Strong safety positioning", "Compact footprint", "Multiple powertrain choices"],
    cons: ["Rear seat width is average", "AMT feel may not suit every buyer"],
    active: true,
    featured: true,
    launchLabel: "Top safety pick",
  },
  {
    id: "model-xuv700",
    brandId: "brand-mahindra",
    categoryId: "cat-car",
    name: "XUV700",
    slug: "xuv700",
    bodyType: "SUV",
    imageUrl:
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=80",
    overview:
      "Mahindra XUV700 is a larger SUV for buyers prioritising space, performance and advanced features. City-wise tax impact can be significant on higher variants.",
    pros: ["Powerful engines", "Seven-seat availability", "Feature-loaded top trims"],
    cons: ["Higher on-road price", "Large footprint for tight city use"],
    active: true,
    featured: true,
  },
  {
    id: "model-450x",
    brandId: "brand-ather",
    categoryId: "cat-ev",
    name: "450X",
    slug: "450x",
    bodyType: "Electric Scooter",
    imageUrl:
      "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=900&q=80",
    overview:
      "Ather 450X is an electric scooter for urban riders who want connected features, quick acceleration and lower running cost. EV pricing depends on city benefits and insurance assumptions.",
    pros: ["Low running cost", "Connected dashboard", "Quick city performance"],
    cons: ["Charging access matters", "Range depends on riding mode"],
    active: true,
    featured: true,
    launchLabel: "EV favorite",
  },
  {
    id: "model-classic-350",
    brandId: "brand-royal-enfield",
    categoryId: "cat-bike",
    name: "Classic 350",
    slug: "classic-350",
    bodyType: "Cruiser Bike",
    imageUrl:
      "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=900&q=80",
    overview: "Royal Enfield Classic 350 is a retro-styled motorcycle for relaxed city and highway riding.",
    pros: ["Relaxed riding posture", "Strong brand pull", "Comfortable cruising"],
    cons: ["Not a sporty commuter", "Weight can feel high in traffic"],
    active: true,
    featured: true,
    launchLabel: "Popular bike",
  },
  {
    id: "model-dost-plus",
    brandId: "brand-ashok-leyland",
    categoryId: "cat-commercial",
    name: "Dost Plus",
    slug: "dost-plus",
    bodyType: "Light Commercial Vehicle",
    imageUrl:
      "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=900&q=80",
    overview: "Ashok Leyland Dost Plus is a light commercial vehicle for city logistics and business load movement.",
    pros: ["Useful payload capacity", "Business-focused utility", "Service network support"],
    cons: ["Comfort is work-focused", "Permit and tax checks matter"],
    active: true,
    featured: true,
    launchLabel: "Business utility",
  },
  {
    id: "model-hiload-ev",
    brandId: "brand-euler",
    categoryId: "cat-ev-commercial",
    name: "HiLoad EV",
    slug: "hiload-ev",
    bodyType: "Electric Cargo Three-Wheeler",
    imageUrl:
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=900&q=80",
    overview: "Euler HiLoad EV is built for electric last-mile cargo use with lower running cost and city fleet suitability.",
    pros: ["Low running cost", "Cargo-focused EV", "Fleet-friendly positioning"],
    cons: ["Charging planning required", "Range depends on load and route"],
    active: true,
    featured: true,
    launchLabel: "EV commercial",
  },
];

const suvSpecs: VehicleSpecifications = {
  engine: {
    displacement: "1493 cc",
    maxPower: "114 bhp",
    maxTorque: "250 Nm",
    cylinders: "4 cylinders",
    driveType: "Front-wheel drive",
    emissionNorm: "BS6 Phase 2",
  },
  dimensions: {
    length: "4330 mm",
    width: "1790 mm",
    height: "1635 mm",
    wheelbase: "2610 mm",
    bootSpace: "433 litres",
    groundClearance: "190 mm",
  },
  interior: {
    upholstery: "Leatherette seats",
    dashboard: "Dual-tone layered dashboard",
    infotainment: "10.25-inch touchscreen",
    speakers: "Premium 8-speaker system",
    airConditioning: "Automatic climate control",
    seatFeatures: "Ventilated front seats",
  },
  exterior: {
    headlamps: "LED headlamps with DRLs",
    wheels: "17-inch alloy wheels",
    roofRails: "Functional roof rails",
    sunroof: "Panoramic sunroof",
  },
  safety: {
    airbags: "6 airbags",
    abs: "ABS with EBD",
    esc: "Electronic stability control",
    camera: "Rear camera with guidelines",
    sensors: "Front and rear parking sensors",
    rating: "5-star safety positioning",
  },
  colors: ["Atlas White", "Abyss Black", "Titan Grey", "Ranger Khaki", "Fiery Red"],
  features: ["Wireless charging", "Connected car tech", "Cruise control", "Drive modes", "Rear AC vents"],
  highlights: ["Strong diesel automatic option", "Feature-rich city SUV", "Good family cabin space"],
};

function carSpecGroups(specs: VehicleSpecifications): SpecificationGroup[] {
  return [
    {
      title: "Engine and performance",
      fields: [
        { label: "Engine", value: specs.engine.displacement },
        { label: "Power", value: specs.engine.maxPower },
        { label: "Torque", value: specs.engine.maxTorque },
        { label: "Drive type", value: specs.engine.driveType },
        { label: "Emission norm", value: specs.engine.emissionNorm },
      ],
    },
    {
      title: "Dimensions and capacity",
      fields: [
        { label: "Length", value: specs.dimensions.length },
        { label: "Width", value: specs.dimensions.width },
        { label: "Height", value: specs.dimensions.height },
        { label: "Wheelbase", value: specs.dimensions.wheelbase },
        { label: "Boot space", value: specs.dimensions.bootSpace },
        { label: "Ground clearance", value: specs.dimensions.groundClearance },
      ],
    },
    {
      title: "Interior and comfort",
      fields: [
        { label: "Upholstery", value: specs.interior.upholstery },
        { label: "Infotainment", value: specs.interior.infotainment },
        { label: "Speakers", value: specs.interior.speakers },
        { label: "Air conditioning", value: specs.interior.airConditioning },
        { label: "Seat features", value: specs.interior.seatFeatures },
      ],
    },
    {
      title: "Safety",
      fields: [
        { label: "Airbags", value: specs.safety.airbags },
        { label: "ABS", value: specs.safety.abs },
        { label: "ESC", value: specs.safety.esc },
        { label: "Camera", value: specs.safety.camera },
        { label: "Sensors", value: specs.safety.sensors },
        { label: "Rating", value: specs.safety.rating },
      ],
    },
  ];
}

function bikeSpecGroups(specs: VehicleSpecifications): SpecificationGroup[] {
  return [
    {
      title: "Engine and performance",
      fields: [
        { label: "Engine", value: specs.engine.displacement },
        { label: "Power", value: specs.engine.maxPower },
        { label: "Torque", value: specs.engine.maxTorque },
        { label: "Drive", value: specs.engine.driveType },
        { label: "Emission norm", value: specs.engine.emissionNorm },
      ],
    },
    {
      title: "Ride, brakes and tyres",
      fields: [
        { label: "Ground clearance", value: specs.dimensions.groundClearance },
        { label: "Wheelbase", value: specs.dimensions.wheelbase },
        { label: "ABS/braking", value: specs.safety.abs },
        { label: "Sensors", value: specs.safety.sensors },
      ],
    },
    {
      title: "Rider features",
      fields: [
        { label: "Console", value: specs.interior.dashboard },
        { label: "Seat", value: specs.interior.seatFeatures },
        { label: "Lighting", value: specs.exterior.headlamps },
      ],
    },
  ];
}

function evTwoWheelerSpecGroups(specs: VehicleSpecifications): SpecificationGroup[] {
  return [
    {
      title: "Battery and motor",
      fields: [
        { label: "Battery", value: specs.engine.displacement },
        { label: "Motor power", value: specs.engine.maxPower },
        { label: "Torque", value: specs.engine.maxTorque },
        { label: "Range", value: specs.features.find((feature) => feature.toLowerCase().includes("range")) },
        { label: "Drive", value: specs.engine.driveType },
      ],
    },
    {
      title: "Charging and connected features",
      fields: [
        { label: "Fast charging", value: specs.features.find((feature) => feature.toLowerCase().includes("charging")) },
        { label: "Dashboard", value: specs.interior.infotainment },
        { label: "Ride modes", value: specs.features.find((feature) => feature.toLowerCase().includes("mode")) },
        { label: "OTA updates", value: specs.features.find((feature) => feature.toLowerCase().includes("ota")) },
      ],
    },
    {
      title: "Practicality",
      fields: [
        { label: "Storage", value: specs.dimensions.bootSpace },
        { label: "Ground clearance", value: specs.dimensions.groundClearance },
        { label: "Safety", value: specs.safety.rating },
      ],
    },
  ];
}

function commercialSpecGroups(specs: VehicleSpecifications): SpecificationGroup[] {
  return [
    {
      title: "Payload and body",
      fields: [
        { label: "Body type", value: "Cargo body" },
        { label: "Cargo space", value: specs.dimensions.bootSpace },
        { label: "Ground clearance", value: specs.dimensions.groundClearance },
        { label: "Wheelbase", value: specs.dimensions.wheelbase },
      ],
    },
    {
      title: "Engine and business use",
      fields: [
        { label: "Engine/battery", value: specs.engine.displacement },
        { label: "Power", value: specs.engine.maxPower },
        { label: "Torque", value: specs.engine.maxTorque },
        { label: "Drive type", value: specs.engine.driveType },
        { label: "Emission", value: specs.engine.emissionNorm },
      ],
    },
    {
      title: "Fleet and operations",
      fields: [
        { label: "Cabin", value: specs.interior.seatFeatures },
        { label: "Fleet feature", value: specs.features.find((feature) => feature.toLowerCase().includes("fleet")) },
        { label: "Running cost", value: specs.features.find((feature) => feature.toLowerCase().includes("running")) },
      ],
    },
  ];
}

const compactSuvSpecs: VehicleSpecifications = {
  ...suvSpecs,
  engine: {
    displacement: "1199 cc",
    maxPower: "118 bhp",
    maxTorque: "170 Nm",
    cylinders: "3 cylinders",
    driveType: "Front-wheel drive",
    emissionNorm: "BS6 Phase 2",
  },
  dimensions: {
    length: "3995 mm",
    width: "1804 mm",
    height: "1620 mm",
    wheelbase: "2498 mm",
    bootSpace: "382 litres",
    groundClearance: "208 mm",
  },
  colors: ["Fearless Purple", "Daytona Grey", "Pristine White", "Flame Red", "Creative Ocean"],
  highlights: ["Compact SUV footprint", "High ground clearance", "Strong safety reputation"],
};

const evScooterSpecs: VehicleSpecifications = {
  engine: {
    displacement: "3.7 kWh battery",
    maxPower: "6.4 kW peak",
    maxTorque: "26 Nm",
    cylinders: "Electric motor",
    driveType: "Belt drive",
    emissionNorm: "Zero tailpipe emissions",
  },
  dimensions: {
    length: "1837 mm",
    width: "739 mm",
    height: "1114 mm",
    wheelbase: "1296 mm",
    bootSpace: "22 litres",
    groundClearance: "153 mm",
  },
  interior: {
    upholstery: "Single-piece stepped seat",
    dashboard: "Digital rider console",
    infotainment: "7-inch touchscreen dashboard",
    speakers: "Not applicable",
    airConditioning: "Not applicable",
    seatFeatures: "Wide rider seat",
  },
  exterior: {
    headlamps: "LED headlamp",
    wheels: "12-inch alloy wheels",
    roofRails: "Not applicable",
    sunroof: "Not applicable",
  },
  safety: {
    airbags: "Not applicable",
    abs: "Combined braking system",
    esc: "Traction control modes",
    camera: "Not applicable",
    sensors: "Side-stand sensor",
    rating: "Battery safety certified",
  },
  colors: ["Space Grey", "Still White", "True Red", "Salt Green", "Lunar Grey"],
  features: ["Fast charging", "Navigation", "Ride modes", "OTA updates", "Reverse assist"],
  highlights: ["Low running cost", "Connected EV dashboard", "City-friendly range"],
};

export const variants: VehicleVariant[] = [
  {
    id: "variant-creta-sx-diesel-at",
    modelId: "model-creta",
    name: "SX Optional Diesel AT",
    slug: "sx-optional-diesel-at",
    exShowroomPrice: 1890000,
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCapacity: "1493 cc",
    mileage: "19.1 km/l",
    seatingCapacity: 5,
    specifications: suvSpecs,
    specificationGroups: carSpecGroups(suvSpecs),
    active: true,
  },
  {
    id: "variant-creta-s-petrol-mt",
    modelId: "model-creta",
    name: "S Petrol MT",
    slug: "s-petrol-mt",
    exShowroomPrice: 1340000,
    fuelType: "Petrol",
    transmission: "Manual",
    engineCapacity: "1497 cc",
    mileage: "17.4 km/l",
    seatingCapacity: 5,
    specifications: {
      ...suvSpecs,
      engine: { ...suvSpecs.engine, displacement: "1497 cc", maxPower: "113 bhp", maxTorque: "144 Nm" },
      interior: { ...suvSpecs.interior, upholstery: "Fabric seats", seatFeatures: "Height-adjustable driver seat" },
      exterior: { ...suvSpecs.exterior, sunroof: "Voice-enabled smart panoramic sunroof" },
      highlights: ["Balanced petrol manual choice", "Comfortable family SUV", "Strong city usability"],
    },
    specificationGroups: carSpecGroups({
      ...suvSpecs,
      engine: { ...suvSpecs.engine, displacement: "1497 cc", maxPower: "113 bhp", maxTorque: "144 Nm" },
      interior: { ...suvSpecs.interior, upholstery: "Fabric seats", seatFeatures: "Height-adjustable driver seat" },
      exterior: { ...suvSpecs.exterior, sunroof: "Voice-enabled smart panoramic sunroof" },
      highlights: ["Balanced petrol manual choice", "Comfortable family SUV", "Strong city usability"],
    }),
    active: true,
  },
  {
    id: "variant-nexon-creative-plus",
    modelId: "model-nexon",
    name: "Creative Plus AMT",
    slug: "creative-plus-amt",
    exShowroomPrice: 1270000,
    fuelType: "Petrol",
    transmission: "AMT",
    engineCapacity: "1199 cc",
    mileage: "17.2 km/l",
    seatingCapacity: 5,
    specifications: compactSuvSpecs,
    specificationGroups: carSpecGroups(compactSuvSpecs),
    active: true,
  },
  {
    id: "variant-xuv700-ax7",
    modelId: "model-xuv700",
    name: "AX7 Luxury Diesel AT",
    slug: "ax7-luxury-diesel-at",
    exShowroomPrice: 2490000,
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCapacity: "2198 cc",
    mileage: "16.6 km/l",
    seatingCapacity: 7,
    specifications: {
      ...suvSpecs,
      engine: { ...suvSpecs.engine, displacement: "2198 cc", maxPower: "182 bhp", maxTorque: "450 Nm" },
      dimensions: { ...suvSpecs.dimensions, length: "4695 mm", width: "1890 mm", height: "1755 mm", bootSpace: "240 litres" },
      interior: { ...suvSpecs.interior, infotainment: "Dual 10.25-inch screens", speakers: "Sony 3D sound system" },
      colors: ["Electric Blue", "Midnight Black", "Everest White", "Dazzling Silver", "Red Rage"],
      features: ["ADAS suite", "Dual-zone climate control", "Memory seats", "Alexa integration", "Wireless Android Auto"],
      highlights: ["Seven-seat SUV", "Powerful diesel automatic", "Advanced driver assistance features"],
    },
    specificationGroups: carSpecGroups({
      ...suvSpecs,
      engine: { ...suvSpecs.engine, displacement: "2198 cc", maxPower: "182 bhp", maxTorque: "450 Nm" },
      dimensions: { ...suvSpecs.dimensions, length: "4695 mm", width: "1890 mm", height: "1755 mm", bootSpace: "240 litres" },
      interior: { ...suvSpecs.interior, infotainment: "Dual 10.25-inch screens", speakers: "Sony 3D sound system" },
      colors: ["Electric Blue", "Midnight Black", "Everest White", "Dazzling Silver", "Red Rage"],
      features: ["ADAS suite", "Dual-zone climate control", "Memory seats", "Alexa integration", "Wireless Android Auto"],
      highlights: ["Seven-seat SUV", "Powerful diesel automatic", "Advanced driver assistance features"],
    }),
    active: true,
  },
  {
    id: "variant-ather-450x-pro",
    modelId: "model-450x",
    name: "450X Pro Pack",
    slug: "450x-pro-pack",
    exShowroomPrice: 149000,
    fuelType: "Electric",
    transmission: "Automatic",
    engineCapacity: "3.7 kWh",
    mileage: "111 km range",
    seatingCapacity: 2,
    specifications: evScooterSpecs,
    specificationGroups: evTwoWheelerSpecGroups(evScooterSpecs),
    active: true,
  },
  {
    id: "variant-classic-350-redditch",
    modelId: "model-classic-350",
    name: "Redditch",
    slug: "redditch",
    exShowroomPrice: 193000,
    fuelType: "Petrol",
    transmission: "Manual",
    engineCapacity: "349 cc",
    mileage: "35 km/l",
    seatingCapacity: 2,
    specifications: {
      ...evScooterSpecs,
      engine: {
        displacement: "349 cc",
        maxPower: "20.2 bhp",
        maxTorque: "27 Nm",
        cylinders: "Single cylinder",
        driveType: "Chain drive",
        emissionNorm: "BS6 Phase 2",
      },
      dimensions: { ...evScooterSpecs.dimensions, bootSpace: "Not applicable", groundClearance: "170 mm" },
      interior: { ...evScooterSpecs.interior, dashboard: "Analog-digital console", infotainment: "Trip meter and fuel display" },
      colors: ["Redditch Red", "Halcyon Black", "Chrome Bronze"],
      features: ["Dual-channel ABS", "USB charging", "Trip meter", "Classic riding posture"],
      highlights: ["Retro cruiser feel", "Strong torque delivery", "Comfortable upright seating"],
    },
    specificationGroups: bikeSpecGroups({
      ...evScooterSpecs,
      engine: {
        displacement: "349 cc",
        maxPower: "20.2 bhp",
        maxTorque: "27 Nm",
        cylinders: "Single cylinder",
        driveType: "Chain drive",
        emissionNorm: "BS6 Phase 2",
      },
      dimensions: { ...evScooterSpecs.dimensions, bootSpace: "Not applicable", groundClearance: "170 mm" },
      interior: { ...evScooterSpecs.interior, dashboard: "Analog-digital console", infotainment: "Trip meter and fuel display" },
      colors: ["Redditch Red", "Halcyon Black", "Chrome Bronze"],
      features: ["Dual-channel ABS", "USB charging", "Trip meter", "Classic riding posture"],
      highlights: ["Retro cruiser feel", "Strong torque delivery", "Comfortable upright seating"],
    }),
    active: true,
  },
  {
    id: "variant-dost-plus-ls",
    modelId: "model-dost-plus",
    name: "LS",
    slug: "ls",
    exShowroomPrice: 785000,
    fuelType: "Diesel",
    transmission: "Manual",
    engineCapacity: "1478 cc",
    mileage: "19.6 km/l",
    seatingCapacity: 2,
    specifications: {
      ...suvSpecs,
      engine: {
        displacement: "1478 cc",
        maxPower: "80 bhp",
        maxTorque: "190 Nm",
        cylinders: "3 cylinders",
        driveType: "Rear-wheel drive",
        emissionNorm: "BS6 Phase 2",
      },
      dimensions: { ...suvSpecs.dimensions, bootSpace: "Payload body", groundClearance: "177 mm" },
      interior: { ...suvSpecs.interior, upholstery: "Vinyl seats", infotainment: "Basic audio optional", seatFeatures: "Driver-focused cabin" },
      colors: ["White", "Blue", "Silver"],
      features: ["Payload body", "Power steering", "Business cabin", "Fleet utility"],
      highlights: ["City logistics friendly", "Useful load bay", "Business-oriented ownership"],
    },
    specificationGroups: commercialSpecGroups({
      ...suvSpecs,
      engine: {
        displacement: "1478 cc",
        maxPower: "80 bhp",
        maxTorque: "190 Nm",
        cylinders: "3 cylinders",
        driveType: "Rear-wheel drive",
        emissionNorm: "BS6 Phase 2",
      },
      dimensions: { ...suvSpecs.dimensions, bootSpace: "Payload body", groundClearance: "177 mm" },
      interior: { ...suvSpecs.interior, upholstery: "Vinyl seats", infotainment: "Basic audio optional", seatFeatures: "Driver-focused cabin" },
      colors: ["White", "Blue", "Silver"],
      features: ["Payload body", "Power steering", "Business cabin", "Fleet utility"],
      highlights: ["City logistics friendly", "Useful load bay", "Business-oriented ownership"],
    }),
    active: true,
  },
  {
    id: "variant-hiload-ev-standard",
    modelId: "model-hiload-ev",
    name: "Standard",
    slug: "standard",
    exShowroomPrice: 390000,
    fuelType: "Electric",
    transmission: "Automatic",
    engineCapacity: "12.4 kWh",
    mileage: "170 km range",
    seatingCapacity: 1,
    specifications: {
      ...evScooterSpecs,
      engine: {
        displacement: "12.4 kWh battery",
        maxPower: "10.9 kW peak",
        maxTorque: "88 Nm",
        cylinders: "Electric motor",
        driveType: "Rear-wheel drive",
        emissionNorm: "Zero tailpipe emissions",
      },
      dimensions: { ...evScooterSpecs.dimensions, bootSpace: "Cargo deck", groundClearance: "300 mm" },
      colors: ["White", "Green", "Blue"],
      features: ["Fast charging", "Fleet telematics", "Cargo body", "Low running cost"],
      highlights: ["Last-mile cargo EV", "Fleet use case", "Low operating cost"],
    },
    specificationGroups: commercialSpecGroups({
      ...evScooterSpecs,
      engine: {
        displacement: "12.4 kWh battery",
        maxPower: "10.9 kW peak",
        maxTorque: "88 Nm",
        cylinders: "Electric motor",
        driveType: "Rear-wheel drive",
        emissionNorm: "Zero tailpipe emissions",
      },
      dimensions: { ...evScooterSpecs.dimensions, bootSpace: "Cargo deck", groundClearance: "300 mm" },
      colors: ["White", "Green", "Blue"],
      features: ["Fast charging", "Fleet telematics", "Cargo body", "Low running cost"],
      highlights: ["Last-mile cargo EV", "Fleet use case", "Low operating cost"],
    }),
    active: true,
  },
];

export const vehicleMedia: VehicleMedia[] = [
  {
    id: "media-creta-front",
    modelId: "model-creta",
    variantId: "variant-creta-sx-diesel-at",
    url: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200&q=85",
    alt: "Hyundai Creta front exterior",
    mediaType: "exterior",
    displayOrder: 1,
    active: true,
  },
  {
    id: "media-creta-side",
    modelId: "model-creta",
    variantId: "variant-creta-sx-diesel-at",
    url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=85",
    alt: "Hyundai Creta side profile",
    mediaType: "exterior",
    displayOrder: 2,
    active: true,
  },
  {
    id: "media-creta-cabin",
    modelId: "model-creta",
    variantId: "variant-creta-sx-diesel-at",
    url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=85",
    alt: "Hyundai Creta cabin",
    mediaType: "interior",
    displayOrder: 3,
    active: true,
  },
  {
    id: "media-creta-white-1",
    modelId: "model-creta",
    variantId: "variant-creta-sx-diesel-at",
    colorName: "Atlas White",
    url: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=1200&q=85",
    alt: "Hyundai Creta Atlas White exterior",
    mediaType: "color",
    displayOrder: 4,
    active: true,
  },
  {
    id: "media-creta-black-1",
    modelId: "model-creta",
    variantId: "variant-creta-sx-diesel-at",
    colorName: "Abyss Black",
    url: "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1200&q=85",
    alt: "Hyundai Creta Abyss Black exterior",
    mediaType: "color",
    displayOrder: 5,
    active: true,
  },
  {
    id: "media-creta-red-1",
    modelId: "model-creta",
    variantId: "variant-creta-sx-diesel-at",
    colorName: "Fiery Red",
    url: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=85",
    alt: "Hyundai Creta Fiery Red exterior",
    mediaType: "color",
    displayOrder: 6,
    active: true,
  },
  {
    id: "media-nexon-front",
    modelId: "model-nexon",
    variantId: "variant-nexon-creative-plus",
    url: "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1200&q=85",
    alt: "Tata Nexon exterior",
    mediaType: "exterior",
    displayOrder: 1,
    active: true,
  },
  {
    id: "media-ather-front",
    modelId: "model-450x",
    variantId: "variant-ather-450x-pro",
    url: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=85",
    alt: "Ather 450X exterior",
    mediaType: "exterior",
    displayOrder: 1,
    active: true,
  },
];

export const heroPromotions: HeroPromotion[] = [
  {
    id: "hero-cars-creta",
    placement: "homepage_hero",
    title: "Hyundai Creta city price spotlight",
    subtitle: "Check SX diesel automatic on-road price with dealer offers.",
    imageUrl: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200&q=85",
    categoryKey: "cars",
    brandId: "brand-hyundai",
    modelId: "model-creta",
    variantId: "variant-creta-sx-diesel-at",
    targetUrl: "/on-road-price?brand=hyundai&model=creta&variant=sx-optional-diesel-at&city=bangalore",
    active: true,
  },
  {
    id: "hero-bikes-classic",
    placement: "homepage_hero",
    title: "Classic 350 on-road price",
    subtitle: "Cruiser bike pricing, specs and city-wise charges.",
    imageUrl: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=85",
    categoryKey: "bikes",
    brandId: "brand-royal-enfield",
    modelId: "model-classic-350",
    variantId: "variant-classic-350-redditch",
    targetUrl: "/on-road-price?brand=royal-enfield&model=classic-350&variant=redditch&city=bangalore",
    active: true,
  },
  {
    id: "hero-commercial-hiload",
    placement: "homepage_hero",
    title: "EV commercial fleet pick",
    subtitle: "Explore electric cargo pricing and business use details.",
    imageUrl: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=1200&q=85",
    categoryKey: "commercial",
    brandId: "brand-euler",
    modelId: "model-hiload-ev",
    variantId: "variant-hiload-ev-standard",
    targetUrl: "/on-road-price?brand=euler-motors&model=hiload-ev&variant=standard&city=bangalore",
    active: true,
  },
];

export const comparisonPages: ComparisonPage[] = [
  {
    id: "cmp-creta-nexon",
    slug: "hyundai-creta-vs-tata-nexon",
    title: "Hyundai Creta vs Tata Nexon",
    cityId: "city-bengaluru",
    vehicle1ModelId: "model-creta",
    vehicle1VariantId: "variant-creta-sx-diesel-at",
    vehicle2ModelId: "model-nexon",
    vehicle2VariantId: "variant-nexon-creative-plus",
    metaTitle: "Hyundai Creta vs Tata Nexon On-Road Price Comparison",
    metaDescription: "Compare Hyundai Creta and Tata Nexon by on-road price, specs, features, mileage, safety and dealer offers.",
    intro: "Creta and Nexon are two popular SUV choices for buyers comparing comfort, city pricing, features and ownership value.",
    verdict: "Choose Creta if you want a larger premium SUV feel and diesel automatic. Choose Nexon if compact size, safety positioning and value are stronger priorities.",
    faq: [
      { question: "Which is cheaper on-road?", answer: "Nexon is cheaper in this seeded comparison, but final city price depends on variant and offers." },
      { question: "Which one is better for family use?", answer: "Creta feels larger, while Nexon is easier to park and manage in dense city use." },
    ],
    showOnHomepage: true,
    showInFooter: true,
    displayOrder: 1,
    active: true,
  },
  {
    id: "cmp-classic-ather",
    slug: "royal-enfield-classic-350-vs-ather-450x",
    title: "Royal Enfield Classic 350 vs Ather 450X",
    cityId: "city-bengaluru",
    vehicle1ModelId: "model-classic-350",
    vehicle1VariantId: "variant-classic-350-redditch",
    vehicle2ModelId: "model-450x",
    vehicle2VariantId: "variant-ather-450x-pro",
    metaTitle: "Classic 350 vs Ather 450X Price and Ownership Comparison",
    metaDescription: "Compare Royal Enfield Classic 350 and Ather 450X by price, running cost, specs, range, features and city use.",
    intro: "This comparison helps buyers decide between a retro petrol cruiser and a connected electric scooter for city use.",
    verdict: "Choose Classic 350 for relaxed cruising and brand feel. Choose Ather 450X for city commuting, low running cost and connected EV features.",
    faq: [
      { question: "Which has lower running cost?", answer: "Ather 450X has lower running cost because it is electric." },
      { question: "Which is better for highway riding?", answer: "Classic 350 is more suitable for relaxed highway riding." },
    ],
    showOnHomepage: true,
    showInFooter: true,
    displayOrder: 2,
    active: true,
  },
];

export const states: State[] = [
  { id: "state-mh", name: "Maharashtra", code: "MH" },
  { id: "state-dl", name: "Delhi", code: "DL" },
  { id: "state-up", name: "Uttar Pradesh", code: "UP" },
  { id: "state-hr", name: "Haryana", code: "HR" },
  { id: "state-ka", name: "Karnataka", code: "KA" },
  { id: "state-tn", name: "Tamil Nadu", code: "TN" },
  { id: "state-ts", name: "Telangana", code: "TS" },
  { id: "state-wb", name: "West Bengal", code: "WB" },
  { id: "state-gj", name: "Gujarat", code: "GJ" },
  { id: "state-rj", name: "Rajasthan", code: "RJ" },
  { id: "state-br", name: "Bihar", code: "BR" },
  { id: "state-jh", name: "Jharkhand", code: "JH" },
  { id: "state-od", name: "Odisha", code: "OD" },
  { id: "state-ch", name: "Chandigarh", code: "CH" },
  { id: "state-mp", name: "Madhya Pradesh", code: "MP" },
  { id: "state-kl", name: "Kerala", code: "KL" },
];

export const cities: City[] = [
  { id: "city-mumbai", stateId: "state-mh", name: "Mumbai", slug: "mumbai", defaultRtoId: "rto-mh-01", tier: "Metro", isMetro: true, rtoStateCode: "MH" },
  { id: "city-pune", stateId: "state-mh", name: "Pune", slug: "pune", defaultRtoId: "rto-mh-pune", tier: "Metro", isMetro: true, rtoStateCode: "MH" },
  { id: "city-nagpur", stateId: "state-mh", name: "Nagpur", slug: "nagpur", defaultRtoId: "rto-mh-nagpur", tier: "Tier 1", isMetro: false, rtoStateCode: "MH" },
  { id: "city-nashik", stateId: "state-mh", name: "Nashik", slug: "nashik", defaultRtoId: "rto-mh-nashik", tier: "Tier 1", isMetro: false, rtoStateCode: "MH" },
  { id: "city-thane", stateId: "state-mh", name: "Thane", slug: "thane", defaultRtoId: "rto-mh-thane", tier: "Tier 1", isMetro: false, rtoStateCode: "MH" },
  { id: "city-new-delhi", stateId: "state-dl", name: "New Delhi", slug: "new-delhi", defaultRtoId: "rto-dl-nd", tier: "Metro", isMetro: true, rtoStateCode: "DL" },
  { id: "city-delhi", stateId: "state-dl", name: "Delhi", slug: "delhi", defaultRtoId: "rto-dl-01", tier: "Metro", isMetro: true, rtoStateCode: "DL" },
  { id: "city-noida", stateId: "state-up", name: "Noida", slug: "noida", defaultRtoId: "rto-up-noida", tier: "Metro", isMetro: true, rtoStateCode: "UP" },
  { id: "city-ghaziabad", stateId: "state-up", name: "Ghaziabad", slug: "ghaziabad", defaultRtoId: "rto-up-ghaziabad", tier: "Tier 1", isMetro: false, rtoStateCode: "UP" },
  { id: "city-gurugram", stateId: "state-hr", name: "Gurugram", slug: "gurugram", defaultRtoId: "rto-hr-gurugram", tier: "Metro", isMetro: true, rtoStateCode: "HR" },
  { id: "city-faridabad", stateId: "state-hr", name: "Faridabad", slug: "faridabad", defaultRtoId: "rto-hr-faridabad", tier: "Tier 1", isMetro: false, rtoStateCode: "HR" },
  { id: "city-bengaluru", stateId: "state-ka", name: "Bengaluru", slug: "bangalore", defaultRtoId: "rto-ka-03", tier: "Metro", isMetro: true, rtoStateCode: "KA" },
  { id: "city-mysuru", stateId: "state-ka", name: "Mysuru", slug: "mysuru", defaultRtoId: "rto-ka-mysuru", tier: "Tier 1", isMetro: false, rtoStateCode: "KA" },
  { id: "city-hubballi-dharwad", stateId: "state-ka", name: "Hubballi-Dharwad", slug: "hubballi-dharwad", defaultRtoId: "rto-ka-hubballi", tier: "Tier 1", isMetro: false, rtoStateCode: "KA" },
  { id: "city-mangaluru", stateId: "state-ka", name: "Mangaluru", slug: "mangaluru", defaultRtoId: "rto-ka-mangaluru", tier: "Tier 1", isMetro: false, rtoStateCode: "KA" },
  { id: "city-chennai", stateId: "state-tn", name: "Chennai", slug: "chennai", defaultRtoId: "rto-tn-chennai", tier: "Metro", isMetro: true, rtoStateCode: "TN" },
  { id: "city-coimbatore", stateId: "state-tn", name: "Coimbatore", slug: "coimbatore", defaultRtoId: "rto-tn-coimbatore", tier: "Tier 1", isMetro: false, rtoStateCode: "TN" },
  { id: "city-madurai", stateId: "state-tn", name: "Madurai", slug: "madurai", defaultRtoId: "rto-tn-madurai", tier: "Tier 1", isMetro: false, rtoStateCode: "TN" },
  { id: "city-tiruchirappalli", stateId: "state-tn", name: "Tiruchirappalli", slug: "tiruchirappalli", defaultRtoId: "rto-tn-trichy", tier: "Tier 1", isMetro: false, rtoStateCode: "TN" },
  { id: "city-salem", stateId: "state-tn", name: "Salem", slug: "salem", defaultRtoId: "rto-tn-salem", tier: "Tier 1", isMetro: false, rtoStateCode: "TN" },
  { id: "city-hyderabad", stateId: "state-ts", name: "Hyderabad", slug: "hyderabad", defaultRtoId: "rto-ts-hyderabad", tier: "Metro", isMetro: true, rtoStateCode: "TS" },
  { id: "city-warangal", stateId: "state-ts", name: "Warangal", slug: "warangal", defaultRtoId: "rto-ts-warangal", tier: "Tier 1", isMetro: false, rtoStateCode: "TS" },
  { id: "city-karimnagar", stateId: "state-ts", name: "Karimnagar", slug: "karimnagar", defaultRtoId: "rto-ts-karimnagar", tier: "Tier 1", isMetro: false, rtoStateCode: "TS" },
  { id: "city-kolkata", stateId: "state-wb", name: "Kolkata", slug: "kolkata", defaultRtoId: "rto-wb-kolkata", tier: "Metro", isMetro: true, rtoStateCode: "WB" },
  { id: "city-howrah", stateId: "state-wb", name: "Howrah", slug: "howrah", defaultRtoId: "rto-wb-howrah", tier: "Tier 1", isMetro: false, rtoStateCode: "WB" },
  { id: "city-durgapur", stateId: "state-wb", name: "Durgapur", slug: "durgapur", defaultRtoId: "rto-wb-durgapur", tier: "Tier 1", isMetro: false, rtoStateCode: "WB" },
  { id: "city-siliguri", stateId: "state-wb", name: "Siliguri", slug: "siliguri", defaultRtoId: "rto-wb-siliguri", tier: "Tier 1", isMetro: false, rtoStateCode: "WB" },
  { id: "city-ahmedabad", stateId: "state-gj", name: "Ahmedabad", slug: "ahmedabad", defaultRtoId: "rto-gj-ahmedabad", tier: "Metro", isMetro: true, rtoStateCode: "GJ" },
  { id: "city-surat", stateId: "state-gj", name: "Surat", slug: "surat", defaultRtoId: "rto-gj-surat", tier: "Tier 1", isMetro: false, rtoStateCode: "GJ" },
  { id: "city-vadodara", stateId: "state-gj", name: "Vadodara", slug: "vadodara", defaultRtoId: "rto-gj-vadodara", tier: "Tier 1", isMetro: false, rtoStateCode: "GJ" },
  { id: "city-rajkot", stateId: "state-gj", name: "Rajkot", slug: "rajkot", defaultRtoId: "rto-gj-rajkot", tier: "Tier 1", isMetro: false, rtoStateCode: "GJ" },
  { id: "city-gandhinagar", stateId: "state-gj", name: "Gandhinagar", slug: "gandhinagar", defaultRtoId: "rto-gj-gandhinagar", tier: "Tier 1", isMetro: false, rtoStateCode: "GJ" },
  { id: "city-jaipur", stateId: "state-rj", name: "Jaipur", slug: "jaipur", defaultRtoId: "rto-rj-jaipur", tier: "Tier 1", isMetro: false, rtoStateCode: "RJ" },
  { id: "city-jodhpur", stateId: "state-rj", name: "Jodhpur", slug: "jodhpur", defaultRtoId: "rto-rj-jodhpur", tier: "Tier 1", isMetro: false, rtoStateCode: "RJ" },
  { id: "city-udaipur", stateId: "state-rj", name: "Udaipur", slug: "udaipur", defaultRtoId: "rto-rj-udaipur", tier: "Tier 1", isMetro: false, rtoStateCode: "RJ" },
  { id: "city-kota", stateId: "state-rj", name: "Kota", slug: "kota", defaultRtoId: "rto-rj-kota", tier: "Tier 1", isMetro: false, rtoStateCode: "RJ" },
  { id: "city-lucknow", stateId: "state-up", name: "Lucknow", slug: "lucknow", defaultRtoId: "rto-up-lucknow", tier: "Tier 1", isMetro: false, rtoStateCode: "UP" },
  { id: "city-kanpur", stateId: "state-up", name: "Kanpur", slug: "kanpur", defaultRtoId: "rto-up-kanpur", tier: "Tier 1", isMetro: false, rtoStateCode: "UP" },
  { id: "city-agra", stateId: "state-up", name: "Agra", slug: "agra", defaultRtoId: "rto-up-agra", tier: "Tier 1", isMetro: false, rtoStateCode: "UP" },
  { id: "city-varanasi", stateId: "state-up", name: "Varanasi", slug: "varanasi", defaultRtoId: "rto-up-varanasi", tier: "Tier 1", isMetro: false, rtoStateCode: "UP" },
  { id: "city-prayagraj", stateId: "state-up", name: "Prayagraj", slug: "prayagraj", defaultRtoId: "rto-up-prayagraj", tier: "Tier 1", isMetro: false, rtoStateCode: "UP" },
  { id: "city-patna", stateId: "state-br", name: "Patna", slug: "patna", defaultRtoId: "rto-br-patna", tier: "Tier 1", isMetro: false, rtoStateCode: "BR" },
  { id: "city-ranchi", stateId: "state-jh", name: "Ranchi", slug: "ranchi", defaultRtoId: "rto-jh-ranchi", tier: "Tier 1", isMetro: false, rtoStateCode: "JH" },
  { id: "city-bhubaneswar", stateId: "state-od", name: "Bhubaneswar", slug: "bhubaneswar", defaultRtoId: "rto-od-bhubaneswar", tier: "Tier 1", isMetro: false, rtoStateCode: "OD" },
  { id: "city-cuttack", stateId: "state-od", name: "Cuttack", slug: "cuttack", defaultRtoId: "rto-od-cuttack", tier: "Tier 1", isMetro: false, rtoStateCode: "OD" },
  { id: "city-chandigarh", stateId: "state-ch", name: "Chandigarh", slug: "chandigarh", defaultRtoId: "rto-ch-chandigarh", tier: "Tier 1", isMetro: false, rtoStateCode: "CH" },
  { id: "city-bhopal", stateId: "state-mp", name: "Bhopal", slug: "bhopal", defaultRtoId: "rto-mp-bhopal", tier: "Tier 1", isMetro: false, rtoStateCode: "MP" },
  { id: "city-indore", stateId: "state-mp", name: "Indore", slug: "indore", defaultRtoId: "rto-mp-indore", tier: "Tier 1", isMetro: false, rtoStateCode: "MP" },
  { id: "city-kochi", stateId: "state-kl", name: "Kochi", slug: "kochi", defaultRtoId: "rto-kl-kochi", tier: "Tier 1", isMetro: false, rtoStateCode: "KL" },
  { id: "city-thiruvananthapuram", stateId: "state-kl", name: "Thiruvananthapuram", slug: "thiruvananthapuram", defaultRtoId: "rto-kl-thiruvananthapuram", tier: "Tier 1", isMetro: false, rtoStateCode: "KL" },
];

export const rtoOffices: RtoOffice[] = cities.map((city, index) => ({
  id: city.defaultRtoId,
  stateId: city.stateId,
  cityId: city.id,
  code: `${city.rtoStateCode ?? states.find((state) => state.id === city.stateId)?.code ?? "XX"}-${String(index + 1).padStart(2, "0")}`,
  name: `${city.name} RTO`,
}));

export const taxRules: StateTaxRule[] = [
  { id: "tax-ka-car-low", stateId: "state-ka", categoryId: "cat-car", minPrice: 0, maxPrice: 1500000, roadTaxPercent: 14, fixedTaxAmount: 0, evExemptionPercent: 0, luxuryCessPercent: 0, active: true },
  { id: "tax-ka-car-high", stateId: "state-ka", categoryId: "cat-car", minPrice: 1500001, roadTaxPercent: 18, fixedTaxAmount: 0, evExemptionPercent: 0, luxuryCessPercent: 1, active: true },
  { id: "tax-ka-ev", stateId: "state-ka", categoryId: "cat-ev", fuelType: "Electric", minPrice: 0, roadTaxPercent: 4, fixedTaxAmount: 0, evExemptionPercent: 75, luxuryCessPercent: 0, active: true },
  { id: "tax-mh-car", stateId: "state-mh", categoryId: "cat-car", minPrice: 0, roadTaxPercent: 13, fixedTaxAmount: 0, evExemptionPercent: 0, luxuryCessPercent: 0, active: true },
  { id: "tax-dl-car", stateId: "state-dl", categoryId: "cat-car", minPrice: 0, roadTaxPercent: 10, fixedTaxAmount: 0, evExemptionPercent: 0, luxuryCessPercent: 0, active: true },
];

export const rtoCharges: RtoCharge[] = cities.map((city) => ({
  id: `charge-${city.id}`,
  stateId: city.stateId,
  cityId: city.id,
  rtoId: city.defaultRtoId,
  registrationFee: city.id === "city-delhi" ? 12000 : 18000,
  smartCardFee: 600,
  numberPlateFee: 1200,
  hypothecationFee: 1500,
  fastagFee: 600,
  handlingCharges: city.id === "city-mumbai" ? 9000 : 7500,
  active: true,
}));

export const insuranceRules: InsuranceRule[] = [
  { id: "ins-car", categoryId: "cat-car", percentOfExShowroom: 3.2, fixedAmount: 15000, active: true },
  { id: "ins-ev", categoryId: "cat-ev", fuelType: "Electric", percentOfExShowroom: 2.4, fixedAmount: 4500, active: true },
];

export const gstRules: GstRule[] = [
  { id: "gst-car", vehicleClass: "car", gstPercent: 28, active: true },
  { id: "gst-bike", vehicleClass: "bike", gstPercent: 28, active: true },
  { id: "gst-scooter", vehicleClass: "scooter", gstPercent: 28, active: true },
  { id: "gst-ev-two-wheeler", vehicleClass: "ev_two_wheeler", gstPercent: 5, active: true },
  { id: "gst-commercial-loading", vehicleClass: "commercial_loading", gstPercent: 28, active: true },
  { id: "gst-commercial-passenger", vehicleClass: "commercial_passenger", gstPercent: 28, active: true },
  { id: "gst-ev-commercial-loading", vehicleClass: "ev_commercial_loading", gstPercent: 5, active: true },
  { id: "gst-ev-commercial-passenger", vehicleClass: "ev_commercial_passenger", gstPercent: 5, active: true },
  { id: "gst-passenger-ev", vehicleClass: "passenger_ev", gstPercent: 5, active: true },
  { id: "gst-loading-ev", vehicleClass: "loading_ev", gstPercent: 5, active: true },
];

export const registrationFeeRules: RegistrationFeeRule[] = [
  { id: "reg-car", vehicleClass: "car", registrationFee: 600, smartCardFee: 200, numberPlateFee: 1200, hypothecationFee: 1500, fastagFee: 600, handlingCharges: 0, active: true },
  { id: "reg-bike", vehicleClass: "bike", registrationFee: 300, smartCardFee: 200, numberPlateFee: 500, hypothecationFee: 1500, fastagFee: 0, handlingCharges: 0, active: true },
  { id: "reg-scooter", vehicleClass: "scooter", registrationFee: 300, smartCardFee: 200, numberPlateFee: 500, hypothecationFee: 1500, fastagFee: 0, handlingCharges: 0, active: true },
  { id: "reg-ev-two-wheeler", vehicleClass: "ev_two_wheeler", registrationFee: 300, smartCardFee: 200, numberPlateFee: 500, hypothecationFee: 1500, fastagFee: 0, handlingCharges: 0, active: true },
  { id: "reg-commercial-loading", vehicleClass: "commercial_loading", registrationFee: 1000, smartCardFee: 300, numberPlateFee: 1200, hypothecationFee: 1500, fastagFee: 600, handlingCharges: 0, active: true },
  { id: "reg-commercial-passenger", vehicleClass: "commercial_passenger", registrationFee: 1000, smartCardFee: 300, numberPlateFee: 1200, hypothecationFee: 1500, fastagFee: 600, handlingCharges: 0, active: true },
  { id: "reg-ev-commercial-loading", vehicleClass: "ev_commercial_loading", registrationFee: 1000, smartCardFee: 300, numberPlateFee: 1200, hypothecationFee: 1500, fastagFee: 0, handlingCharges: 0, active: true },
  { id: "reg-ev-commercial-passenger", vehicleClass: "ev_commercial_passenger", registrationFee: 1000, smartCardFee: 300, numberPlateFee: 1200, hypothecationFee: 1500, fastagFee: 0, handlingCharges: 0, active: true },
  { id: "reg-passenger-ev", vehicleClass: "passenger_ev", registrationFee: 1000, smartCardFee: 300, numberPlateFee: 1200, hypothecationFee: 1500, fastagFee: 0, handlingCharges: 0, active: true },
  { id: "reg-loading-ev", vehicleClass: "loading_ev", registrationFee: 1000, smartCardFee: 300, numberPlateFee: 1200, hypothecationFee: 1500, fastagFee: 0, handlingCharges: 0, active: true },
];

export const dealers: Dealer[] = [
  { id: "dealer-green-bengaluru", name: "Greenline Hyundai Bengaluru", slug: "greenline-hyundai-bengaluru", cityId: "city-bengaluru", area: "Whitefield", contactPerson: "Anita Rao", phone: "+91 98765 43001", email: "leads@greenline.example", active: true, verified: true, priority: 2 },
  { id: "dealer-trust-mumbai", name: "TrustDrive Motors Mumbai", slug: "trustdrive-motors-mumbai", cityId: "city-mumbai", area: "Andheri East", contactPerson: "Rahul Shah", phone: "+91 98765 43002", email: "sales@trustdrive.example", active: true, verified: true, priority: 1 },
  { id: "dealer-ev-delhi", name: "EV Avenue Delhi", slug: "ev-avenue-delhi", cityId: "city-delhi", area: "Saket", contactPerson: "Meera Sethi", phone: "+91 98765 43003", email: "hello@evavenue.example", active: true, verified: true, priority: 3 },
];

export const dealerBrandMappings: DealerBrandMapping[] = [
  { id: "map-hyundai-bengaluru", dealerId: "dealer-green-bengaluru", brandId: "brand-hyundai", cityId: "city-bengaluru", active: true },
  { id: "map-tata-mumbai", dealerId: "dealer-trust-mumbai", brandId: "brand-tata", cityId: "city-mumbai", active: true },
  { id: "map-mahindra-mumbai", dealerId: "dealer-trust-mumbai", brandId: "brand-mahindra", cityId: "city-mumbai", active: true },
  { id: "map-ather-delhi", dealerId: "dealer-ev-delhi", brandId: "brand-ather", cityId: "city-delhi", active: true },
];

export const offers: Offer[] = [
  {
    id: "offer-creta-bangalore",
    title: "Dealer exchange bonus",
    description: "Exchange bonus available through mapped Hyundai dealer in Bengaluru.",
    brandId: "brand-hyundai",
    modelId: "model-creta",
    cityId: "city-bengaluru",
    dealerId: "dealer-green-bengaluru",
    discountAmount: 25000,
    sponsorType: "dealer",
    placement: "dealer_card",
    active: true,
  },
  {
    id: "offer-creta-accessory",
    title: "Free accessory kit",
    description: "Dealer-provided accessory package on selected Creta variants this month.",
    brandId: "brand-hyundai",
    modelId: "model-creta",
    cityId: "city-bengaluru",
    dealerId: "dealer-green-bengaluru",
    discountAmount: 15000,
    sponsorType: "dealer",
    placement: "dealer_card",
    active: true,
  },
  {
    id: "offer-ev-delhi",
    title: "EV city benefit estimate",
    description: "Indicative EV benefit reflected in the city price estimate.",
    brandId: "brand-ather",
    modelId: "model-450x",
    cityId: "city-delhi",
    dealerId: "dealer-ev-delhi",
    discountAmount: 12000,
    sponsorType: "dealer",
    placement: "dealer_card",
    active: true,
  },
];

export const seoPages: SeoPage[] = [
  {
    id: "seo-creta-bangalore",
    slug: "hyundai-creta-on-road-price-in-bangalore",
    pageKind: "model_price",
    title: "Hyundai Creta On-Road Price in Bangalore",
    h1: "Hyundai Creta on-road price in Bangalore",
    metaTitle: "Hyundai Creta On-Road Price in Bangalore | AutoPrice",
    metaDescription: "Check Hyundai Creta variant-wise on-road price in Bangalore with tax, RTO, insurance and dealer enquiry.",
    intro: "Compare Hyundai Creta variants with transparent Bangalore on-road pricing before visiting the showroom.",
    body: "This page uses live variant prices and Karnataka tax assumptions from the platform pricing engine. Final dealer quote may vary based on accessories, insurance plan and offers.",
    faq: [
      { question: "Does this include road tax?", answer: "Yes. The estimate includes road tax, RTO fees, insurance and common handling charges." },
      { question: "Can I contact a dealer?", answer: "Yes. Submit an enquiry and the platform routes it to admin and a matched verified dealer when available." },
    ],
    filters: { cityId: "city-bengaluru", brandId: "brand-hyundai", modelId: "model-creta" },
    showOnHomepage: true,
    showInFooter: true,
    active: true,
  },
  {
    id: "seo-ev-delhi",
    slug: "electric-scooters-in-delhi",
    pageKind: "ev",
    title: "Electric Scooters in Delhi",
    h1: "Electric scooters on-road price in Delhi",
    metaTitle: "Electric Scooters in Delhi | On-Road Price",
    metaDescription: "Discover electric scooter pricing, EV benefits, insurance and dealer enquiry options in Delhi.",
    intro: "Explore EV scooter prices with clean pricing breakdowns and verified dealer routing.",
    body: "EV pricing can change with state incentives and availability. Use this page for planning and confirm final price with the assigned dealer.",
    faq: [{ question: "Are EV exemptions included?", answer: "Applicable EV road-tax relief is reflected when configured in admin tax rules." }],
    filters: { cityId: "city-delhi", categoryId: "cat-ev", fuelType: "Electric" },
    showOnHomepage: true,
    showInFooter: true,
    active: true,
  },
];

export const leads: VehicleLead[] = [
  {
    id: "lead-sample-1",
    name: "Sample Buyer",
    phone: "+91 90000 00000",
    email: "buyer@example.com",
    cityId: "city-bengaluru",
    brandId: "brand-hyundai",
    modelId: "model-creta",
    variantId: "variant-creta-sx-diesel-at",
    selectedOnRoadPrice: 2215000,
    preferredContactTime: "Evening",
    message: "Interested in SX Optional Diesel AT.",
    assignedDealerId: "dealer-green-bengaluru",
    status: "assigned",
    source: "pricing_page",
    createdAt: new Date().toISOString(),
  },
];
